{
 "title": "dz_№47",
 "time": { "from": "2022-06-29T16:22:10.186Z", "to": "2022-06-29T17:06:02.828Z" },
 "panels": [
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100*(1-avg by(instance) (irate(node_cpu_seconds_total{instance=\"node_exporter:9100\", mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{__name__}}" },
    { "expr": "node_load5", "legendFormat": "{{__name__}}" },
    { "expr": "node_load15", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Free Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100-(100 *((node_filesystem_avail_bytes)/(node_filesystem_size_bytes{ mountpoint=\"/boot\",fstype!=\"tmpfs\"})))",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100-(100 *((node_filesystem_avail_bytes)/(node_filesystem_size_bytes{ mountpoint=\"/\",fstype!=\"tmpfs\"})))",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100-(100 *((node_filesystem_avail_bytes)/(node_filesystem_size_bytes{ mountpoint=\"/home\",fstype!=\"tmpfs\"})))",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100-(100 *((node_filesystem_avail_bytes)/(node_filesystem_size_bytes{ mountpoint=\"/var\",fstype!=\"tmpfs\"})))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/on (instance) node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}